version: '2'
services:
  zookeeper:
    image: zookeeper:latest
    ports:
     - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    ports:
     - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_MESSAGE_MAX_BYTES: 2000000 # Increased max message size
      KAFKA_REPLICA_FETCH_MAX_BYTES: 2000000 # Increased max fetch size
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./kafka_data:/kafka

  kafkamanager:
    image: hlebalbau/kafka-manager:latest
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:2181

  producer:
    build: ./producer
    container_name: stock_producer
    volumes:
      - ./producer:/app
    working_dir: /app
    depends_on:
      - kafka
    restart: always

  consumer:
    build: ./consumer
    container_name: stock_consumer
    volumes:
      - ./consumer:/app
    working_dir: /app
    depends_on:
      - kafka
    restart: always
